org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5

# Mod Properties
mod_version=26.1-r1.0
maven_group=net.rebel459.remnants
archives_base_name=remnants

# Dependencies
fabric_version=0.144.3+26.1
frozenlib_version=2.4.3-mc26.1
trailier_version=1.2.5-mc26.1